'use strict';
const $=s=>document.querySelector(s), canvas=$('#world'),ctx=canvas.getContext('2d'),dialog=$('#dialog'),content=$('#content');
const KEY='harmoni-kesederhanaan-v1';
const fresh=()=>({done:{},attempts:{},feelings:{},score:0,name:'',sound:false,bonus:false,reflection:0,ways:[],emotion:'',pledges:[],finished:false});
let state=fresh();try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.done&&s.attempts&&s.feelings)state={...state,...s};}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('#storage').textContent='Kemajuan sesi ini tidak dapat disimpan pada peranti ini.';}update();}
const missions=[
{name:'Mei Ling',title:'Membeli Hadiah',place:'Pasar Raya',x:825,y:376,color:'#EF476F',skin:'#edbc94',hair:1,q:'Salam! Saya hendak membeli hadiah untuk Hari Keluarga. Saya mempunyai wang yang terhad. Apakah yang patut saya lakukan?',opts:['🎁 Membeli hadiah paling mahal supaya semua orang kagum.','🎁 Membeli hadiah yang sesuai dengan jumlah wang yang diperuntukkan.','🎁 Membeli banyak hadiah walaupun terpaksa meminjam wang.'],why:'Kita perlu bersederhana dalam perbelanjaan dengan membeli barang mengikut kemampuan dan keperluan.',fq:'Apakah perasaan kamu apabila dapat menggunakan wang secara sederhana?',feel:['😊 Gembira','😌 Tenang','🥰 Bersyukur']},
{name:'Kumar',title:'Majlis Hari Keluarga',place:'Dewan Komuniti',x:500,y:376,color:'#8056b9',skin:'#a46943',q:'Kita akan menghadiri Majlis Hari Keluarga. Apakah pakaian yang paling sesuai?',opts:['👑 💍 🕶️ Pakaian terlalu berlebihan dengan banyak aksesori.','👕 👖 Pakaian yang sopan, kemas dan sesuai dengan majlis.','🩳 🩴 Pakaian yang tidak sesuai dengan suasana majlis.'],why:'Kesederhanaan dalam penampilan bermaksud berpakaian kemas, sopan dan sesuai dengan keadaan.',fq:'Bagaimanakah perasaan kamu apabila berpakaian sopan dan sesuai?',feel:['😊 Selesa','😄 Gembira','👍 Yakin']},
{name:'Teck Seng',title:'Pusat Internet Desa',place:'Pusat Internet',x:500,y:795,color:'#4EA8DE',skin:'#e9b183',q:'Saya suka bermain permainan komputer. Hari ini saya sudah bermain agak lama. Apakah yang patut saya lakukan?',opts:['Terus bermain sepanjang hari.','Berhenti seketika dan bahagikan masa untuk belajar, berehat dan melakukan aktiviti lain.','Gunakan semua komputer supaya orang lain tidak dapat menggunakannya.'],why:'Bersederhana dalam penggunaan kemudahan bermaksud menggunakannya dalam tempoh yang sesuai dan memberi peluang kepada orang lain.',fq:'Apakah perasaan kamu apabila semua orang mendapat peluang menggunakan kemudahan awam?',feel:['😊 Gembira','🤝 Puas hati','❤️ Senang hati']},
{name:'Aisyah',title:'Jamuan Masyarakat',place:'Rumah Terbuka',x:500,y:585,color:'#dd8748',skin:'#c89061',hair:2,q:'Pelbagai makanan disediakan untuk tetamu. Apakah cara makan yang menunjukkan kesederhanaan?',opts:['Mengambil makanan sebanyak mungkin walaupun tidak mampu menghabiskannya.','Mengambil makanan mengikut keperluan dan berhenti sebelum terlalu kenyang.','Mengambil semua makanan kegemaran supaya orang lain tidak sempat mendapatkannya.'],why:'Kesederhanaan dalam pemakanan bermaksud mengambil makanan secukupnya dan mengelakkan pembaziran.',fq:'Bagaimanakah perasaan kamu apabila makanan tidak dibazirkan?',feel:['🥰 Bersyukur','😊 Gembira','😌 Puas hati']},
{name:'Ravi',title:'Taman Komuniti',place:'Taman Rekreasi',x:500,y:173,color:'#2b9761',skin:'#955d3d',q:'Beberapa orang sedang menggunakan taman. Rakan kamu mahu bermain sambil menjerit kuat dan mengganggu orang lain. Apakah tindakan kamu?',opts:['Menjerit lebih kuat supaya permainan lebih seronok.','Bermain dengan tertib dan menjaga suara supaya tidak mengganggu orang lain.','Menyuruh semua orang lain meninggalkan taman.'],why:'Bersederhana dalam perlakuan bermaksud menjaga tingkah laku supaya tidak mengganggu keselesaan orang lain.',fq:'Apakah perasaan kamu apabila dapat menjaga keselesaan orang lain?',feel:['😊 Gembira','💗 Bangga','😌 Tenang']}
];
const bonus={name:'Pak Cik Rahman',x:770,y:655,color:'#ae753b',skin:'#bf865b',q:'Kamu berjumpa dengan jiran yang lebih tua. Bagaimanakah kamu patut berkomunikasi?',opts:['Bercakap sesuka hati tanpa memikirkan perasaan orang.','Bercakap dengan sopan, sederhana dan menghormati orang lain.','Tidak menghiraukan mereka.'],why:'Kesederhanaan dalam pertuturan membantu menjaga perasaan orang lain dan mewujudkan hubungan masyarakat yang harmoni.'};
let player={x:170,y:379},keys={},nearest=null,last=0,lastStep=0,audio;
const buildings=[{x:85,y:250,w:170,h:88,label:'RUMAH',icon:'🏠',color:'#e89b69'},{x:405,y:242,w:190,h:96,label:'DEWAN KOMUNITI',icon:'🎉',color:'#d892aa'},{x:735,y:250,w:180,h:88,label:'PASAR RAYA',icon:'🛒',color:'#63b4c1'},{x:405,y:455,w:190,h:94,label:'RUMAH TERBUKA',icon:'🍽️',color:'#e9b85d'},{x:405,y:666,w:190,h:94,label:'PUSAT INTERNET',icon:'💻',color:'#7da9d0'},{x:695,y:550,w:170,h:65,label:'BALAI KOMUNITI',icon:'🏫',color:'#baab86'}];
const trees=[[80,100],[230,110],[745,100],[895,130],[70,550],[250,605],[120,760],[820,790],[920,500],[340,745],[655,790],[660,120]], benches=[{x:374,y:108,w:62,h:22},{x:565,y:108,w:62,h:22}],fences=[{x:40,y:440,w:230,h:12},{x:725,y:440,w:230,h:12}];
function count(){return missions.filter((_,i)=>state.done[i]).length;}
function update(){$('#score').textContent=`⭐ ${state.score} / 100 mata`;$('#progress').textContent=`🎯 ${count()} / 5 misi`;$('#missions').innerHTML=missions.map((m,i)=>`<li>${state.done[i]?'✅':'⬜'} ${m.title}<br><small>${m.name} · ${m.place}</small></li>`).join('');$('#sound').textContent=state.sound?'🔊 Bunyi ON':'🔇 Bunyi OFF';$('#reflect').hidden=!state.bonus||state.finished;$('#achievement').hidden=!state.finished;}
function tone(freq=500){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.15);}catch{}}
function show(html,closable=true){keys={};content.innerHTML=html;$('#close').hidden=!closable;if(!dialog.open)dialog.showModal();}
function button(label,fn,cls='primary'){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;content.append(b);return b;}
function close(){dialog.close();keys={};canvas.focus();}
$('#close').onclick=close;dialog.addEventListener('close',()=>{keys={};});
function mission(i){const m=i===5?bonus:missions[i];tone(440);if(i===5&&state.bonus){reflection();return;}if(state.done[i]){show(`<small>✅ MISI SELESAI</small><h2>${m.name}</h2><p>${m.why}</p><p>Perasaan kamu: ${state.feelings[i]}</p>`);return;}
show(`<small>${i===5?'MISI BONUS':m.place.toUpperCase()}</small><h2>💬 ${m.name}</h2><p>${m.q}</p><div id="feedback" role="status"></div>`);
m.opts.forEach((opt,j)=>button(`${'ABC'[j]}. ${opt}`,()=>{if(j!==1){state.attempts[i]=true;save();tone(220);$('#feedback').className='feedback';$('#feedback').textContent='💡 Cuba fikirkan semula. Pilih tindakan yang tidak berlebihan, mengikut keperluan dan menjaga keselesaan orang lain.';return;}tone(750);if(i===5){state.bonus=true;save();show(`<h2>✅ Bijak!</h2><p>${m.why}</p>`);button('🌱 Mulakan refleksi',reflection);return;}
const points=state.attempts[i]?10:20;show(`<h2>✅ Tepat! +${points} mata</h2><p>${m.why}</p><h3>💗 ${m.fq}</h3><p>Pilih perasaan kamu untuk melengkapkan misi.</p>`);m.feel.forEach(feel=>button(feel,()=>{if(state.done[i])return;state.done[i]=points;state.feelings[i]=feel;state.score=Object.values(state.done).reduce((a,b)=>a+b,0);save();tone(900);show(`<h2>🌟 Misi selesai!</h2><p>Bagus! Kamu berasa ${feel.split(' ').slice(1).join(' ').toLowerCase()} apabila mengamalkan kesederhanaan.</p><p>${count()===5?'Kelima-lima misi selesai! Jumpa Pak Cik Rahman di Balai Komuniti untuk misi bonus.':'Teruskan perjalanan untuk membantu penduduk lain.'}</p>`);button('Teruskan jelajah',close);}));},'answer'));
}
function interact(){if(!dialog.open&&nearest)mission(nearest.index);}
$('#interact').onclick=interact;
const ways=['Berbelanja mengikut kemampuan.','Berpakaian secara sopan dan sesuai.','Menggunakan kemudahan awam dengan sederhana.','Mengambil makanan mengikut keperluan.','Bertutur dan berkelakuan dengan sopan.','Menggunakan sesuatu secara berlebihan.'];
function checks(list){return list.map((t,i)=>`<label><input type="checkbox" value="${i}">${t}</label>`).join('');}
function reflection(){if(state.finished){ending();return;}if(state.reflection===0){show('<small>REFLEKSI · SP 13.2</small><h2>🧠 Apa yang saya pelajari?</h2><p>Pilih TIGA cara kamu boleh mengamalkan kesederhanaan dalam hidup bermasyarakat.</p>'+checks(ways)+'<p id="validation" role="status"></p>');button('Semak pilihan',()=>{const selected=[...content.querySelectorAll('input:checked')].map(x=>+x.value);if(selected.length!==3||selected.includes(5)){$('#validation').textContent='Pilih tepat tiga amalan yang tidak berlebihan. Cuba lagi!';return;}state.ways=selected.map(i=>ways[i]);state.reflection=1;save();reflection();});}
else if(state.reflection===1){show('<small>REFLEKSI · SP 13.4</small><h2>💗 Perasaan saya</h2><p>Syabas! Kamu dapat mengenal pasti cara mengamalkan kesederhanaan.</p><p>Selepas membantu penduduk Kampung Harmoni, apakah perasaan kamu?</p>');['😊 Gembira','🥰 Bangga','😌 Tenang','🙏 Bersyukur','❤️ Senang hati'].forEach(e=>button(e,()=>{state.emotion=e;state.reflection=2;save();reflection();}));}
else{show(`<small>REFLEKSI · SP 13.5</small><h2>🌱 Janji kesederhanaan saya</h2><p>Saya berasa ${state.emotion} apabila dapat mengamalkan sikap sederhana kerana tindakan saya dapat menjaga keharmonian masyarakat.</p><p>Saya akan mengamalkan kesederhanaan dengan… (pilih sekurang-kurangnya satu)</p>`+checks(ways.slice(0,5))+'<p id="validation" role="status"></p>');button('Selesaikan pengembaraan',()=>{const selected=[...content.querySelectorAll('input:checked')];if(!selected.length){$('#validation').textContent='Pilih sekurang-kurangnya satu janji kamu.';return;}state.pledges=selected.map(x=>ways[+x.value]);state.finished=true;save();ending();});}}
function ending(){show('<h2>🏆 Tahniah, Juara Kesederhanaan!</h2><p>Mengamalkan kesederhanaan membantu kita hidup dengan selesa, menjaga perasaan orang lain dan mewujudkan masyarakat yang harmoni.</p><p>⭐ Mata: '+state.score+'/100 · 🎯 Misi: 5/5</p><label>Nama untuk sijil<input id="name" type="text" maxlength="60" autocomplete="off" placeholder="Taip nama kamu"></label><p id="validation" role="status"></p>');$('#name').value=state.name;button('📜 Lihat pencapaian',()=>{const name=$('#name').value.trim();if(!name){$('#validation').textContent='Taip nama kamu dahulu.';return;}state.name=name;save();certificate();});button('🔄 Main semula',reset,'quiet');tone(1000);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){$('#confetti').innerHTML=Array.from({length:35},(_,i)=>`<i class="flake" style="left:${Math.random()*100}%;background:${['#FFD166','#4EA8DE','#06D6A0','#EF476F'][i%4]};animation-delay:${Math.random()}s"></i>`).join('');setTimeout(()=>$('#confetti').replaceChildren(),4500);}}
function certificate(){show(`<div class="certificate"><p>🏆 SIJIL DIGITAL 🏆</p><h2>JUARA KESEDERHANAAN</h2><strong id="certname"></strong><p>Tahniah kerana berjaya menyelesaikan<br>Misi Kesederhanaan: Kampung Harmoni!</p><p>⭐ Mata: ${state.score}/100<br>🎯 Misi: 5/5</p><b>Nilai: KESEDERHANAAN</b><p>Pendidikan Moral Tahun 5</p></div>`);$('#certname').textContent=state.name;button('🖨️ Cetak / Simpan PDF',()=>window.print());}
function reset(){show('<h2>Reset permainan?</h2><p>Mata, nama, misi dan refleksi yang disimpan akan dipadamkan.</p>');button('Ya, mula semula',()=>{state=fresh();player={x:170,y:379};save();intro();});button('Batal',close,'quiet');}
function intro(){show('<small>PENDIDIKAN MORAL · TAHUN 5</small><h2>🌟 Misi Kesederhanaan:<br>Kampung Harmoni</h2><p>Selamat datang ke Kampung Harmoni! Hari Komuniti akan berlangsung tidak lama lagi.</p><p>Penduduk memerlukan bantuan kamu untuk membuat keputusan yang menunjukkan amalan kesederhanaan. Jelajah kampung, berbual dengan penduduk dan selesaikan semua misi.</p><p>Adakah kamu bersedia menjadi <b>JUARA KESEDERHANAAN?</b></p>',false);button(count()?'▶ Sambung misi':'▶ Mula misi',close);}
$('#reset').onclick=reset;$('#sound').onclick=()=>{state.sound=!state.sound;save();tone();};$('#reflect').onclick=reflection;$('#achievement').onclick=ending;
$('#teacher').onclick=()=>{show(`<h2>👩‍🏫 Mod guru</h2><p><b>Standard Kandungan 13.0</b><br>Amalan Kesederhanaan dalam Hidup Bermasyarakat</p><p><b>13.2</b> Menjelaskan cara amalan kesederhanaan dalam hidup bermasyarakat.<br><b>13.4</b> Mengekspresikan perasaan berkaitan dengan amalan kesederhanaan dalam hidup bermasyarakat.<br><b>13.5</b> Mengamalkan sikap sederhana dalam hidup bermasyarakat.</p><p>Standard dipetik daripada bahan yang diberikan. Simulasi dan janji murid perlu disusuli pemerhatian amalan sebenar.</p><ul>${missions.map((m,i)=>`<li>${state.done[i]?'✅':'⬜'} ${m.title} · ${state.done[i]||0} mata${state.feelings[i]?' · '+state.feelings[i]:''}</li>`).join('')}</ul><p><b>Mata: ${state.score}/100</b><br>Bonus: ${state.bonus?'Selesai':'Belum selesai'}<br>Refleksi: ${state.finished?'Selesai':'Belum selesai'}</p><p>Cara dipilih: ${state.ways.join(' ')||'—'}</p><p>Perasaan akhir: ${state.emotion||'—'}</p><p>Janji: ${state.pledges.join(' ')||'—'}</p><p>20 mata: betul kali pertama; 10 mata: selepas mencuba semula. Bonus dan refleksi tidak menambah mata. Rekod ini hanya untuk pemain pada pelayar ini.</p>`);};
function rect(x,y,w,h,c,r=10){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function text(t,x,y,size=18,color='#264653'){ctx.fillStyle=color;ctx.font=`bold ${size}px Trebuchet MS,Arial`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function person(p,label,done=false,isPlayer=false){ctx.fillStyle='#26465322';ctx.beginPath();ctx.ellipse(p.x,p.y+12,18,7,0,0,7);ctx.fill();rect(p.x-10,p.y-7,20,22,p.color||'#fff',6);rect(p.x-10,p.y+12,7,11,'#264653',2);rect(p.x+3,p.y+12,7,11,'#264653',2);if(p.hair)circle(p.x,p.y-20,17,p.hair===2?'#f6d8ab':'#292d39');circle(p.x,p.y-22,12,p.skin||'#cd966b');rect(p.x-12,p.y-35,24,8,p.hair===2?'#f6d8ab':'#292d39',5);circle(p.x-4,p.y-23,1.5,'#26343c');circle(p.x+4,p.y-23,1.5,'#26343c');if(isPlayer){circle(p.x,p.y-50,12,'#176451');text('▼',p.x,p.y-45,16,'white');}else{text(done?'✅':'💬',p.x,p.y-48,24);}const width=ctx.measureText(label).width+24;rect(p.x-width/2,p.y+28,width,27,'#fffdf0',8);text(label,p.x,p.y+47,17);}
function draw(){ctx.clearRect(0,0,1000,880);rect(0,0,1000,880,'#d9efb7',0);for(let x=20;x<1000;x+=44)for(let y=25;y<880;y+=48){text('ˇ',x,y,12,'#a7ce8c');}rect(115,357,770,65,'#f8e5b9',22);rect(463,135,74,700,'#f8e5b9',22);rect(505,636,285,52,'#f8e5b9',20);rect(346,45,310,115,'#bfdfa2',25);text('🌳 TAMAN REKREASI',500,77,23);benches.forEach(b=>{rect(b.x,b.y,b.w,b.h,'#b78659',4);});fences.forEach(f=>{rect(f.x,f.y,f.w,f.h,'#e6cc9e',3);for(let x=f.x;x<f.x+f.w;x+=25)rect(x,f.y-9,8,27,'#c19662',2);});trees.forEach(([x,y])=>{rect(x-6,y-5,12,35,'#a38158',3);circle(x,y-20,27,'#58a96d');circle(x-13,y-27,19,'#77bd76');});buildings.forEach(b=>{rect(b.x+5,b.y+9,b.w,b.h,'#26465318');rect(b.x,b.y,b.w,b.h,'#fff4d9',7);rect(b.x-8,b.y-16,b.w+16,30,b.color,6);rect(b.x+b.w/2-13,b.y+b.h-35,26,35,'#92765d',3);for(const xx of [b.x+22,b.x+b.w-47]){rect(xx,b.y+30,25,24,'#a8dce1',4);}text(b.icon,b.x+b.w/2,b.y+44,31);text(b.label,b.x+b.w/2,b.y-29,18);});text('🌼 🌸 🌼',185,501,28);text('🌼 🌸 🌼',810,485,28);text('☁️',310,70,39);text('☁️',850,55,42);rect(305,304,8,40,'#78948b',2);circle(309,301,10,'#fff6bd');rect(665,333,21,27,'#6f9b82',4);missions.forEach((m,i)=>person(m,m.name,!!state.done[i]));if(count()===5)person(bonus,bonus.name,state.bonus);person(player,'PEMAIN',false,true);}
function blocked(x,y){if(x<23||x>977||y<30||y>850)return true;const boxes=[...buildings,...benches,...fences,{x:301,y:300,w:16,h:45},{x:665,y:333,w:21,h:27}];if(boxes.some(b=>x>b.x-14&&x<b.x+b.w+14&&y>b.y-15&&y<b.y+b.h+15))return true;if(trees.some(([tx,ty])=>Math.hypot(x-tx,y-(ty-8))<37))return true;return [...missions,...(count()===5?[bonus]:[])].some(n=>Math.hypot(x-n.x,y-n.y)<31);}
function loop(time){const dt=Math.min((time-last)/1000,.035);last=time;if(!dialog.open){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);const length=Math.hypot(dx,dy)||1;dx=dx/length*185*dt;dy=dy/length*185*dt;if(!blocked(player.x+dx,player.y))player.x+=dx;if(!blocked(player.x,player.y+dy))player.y+=dy;if((dx||dy)&&time-lastStep>330){tone(130);lastStep=time;}}
nearest=[...missions,...(count()===5?[bonus]:[])].map((m,index)=>({...m,index,d:Math.hypot(player.x-m.x,player.y-m.y)})).filter(m=>m.d<85).sort((a,b)=>a.d-b.d)[0];$('#hint').textContent=nearest?`💬 ${nearest.name} · Tekan E atau INTERAKSI`:count()===5&&!state.bonus?'🧭 Jumpa Pak Cik Rahman di Balai Komuniti.':'🧭 Dekati penduduk untuk berbual.';$('#interact').disabled=!nearest;draw();requestAnimationFrame(loop);}
window.addEventListener('keydown',e=>{if(dialog.open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','e'].includes(k)){e.preventDefault();keys[k]=true;if(k==='e'&&!e.repeat)interact();}});window.addEventListener('keyup',e=>{keys[e.key.length===1?e.key.toLowerCase():e.key]=false;});window.addEventListener('blur',()=>keys={});document.addEventListener('visibilitychange',()=>keys={});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{keys[b.dataset.key]=false;};});
update();intro();requestAnimationFrame(loop);
